### ISSUE TITLE
This is now an error according to policy CMP0004

### ISSUE THREAD

**Issue by kkyyds1** [IgnacioVellido/HPDL-Planner#2]
![image](https://user-images.githubusercontent.com/128840869/230290788-55b03afe-c63b-46c7-8b46-88f70f7b9363.png)
I get the Cmake Error when I execute command "cmake .". And my cmake version is 3.26.1.
What is wrong?
![image](https://user-images.githubusercontent.com/128840869/230291376-49160949-bafe-45a2-93e9-7679c8f67643.png)

**Comment by gorgueugr** [comment]
Hi @kkyyds1,
Thank you for reporting the issue. I have made some changes to fix it and im now waiting to have permissions to merge.
Jorge
